feat: add rules ks-admission-general-block-nodeport-services&ks-admission-general-container-resource-limits
casbin/kubesphere-authz pull request #8
Opened 2021-08-18 08:33 UTC by ComradeProgrammer

feat: add rules ks-admission-general-block-nodeport-services&ks-admission-general-container-resource-limits

2021-08-18 08:43 UTC, ComradeProgrammer commented
part of the implementation of #4

2021-08-18 09:06 UTC, sagilio commented on .vscode/settings.json
> +    //"go.testFlags": ["-v"]
`.vscode` directory should be added in `.gitignore`.

2021-08-18 09:07 UTC, sagilio commented on example/casbinconfig/allowed_repo.conf
> +m= r.namespace == p.namespace && r.image == p.image
`m = r.namespace == p.namespace && r.image == p.image`

2021-08-18 09:08 UTC, sagilio commented on example/casbinconfig/container_resource_limit.conf
> +e=some(where (p.eft == allow))
e = some(where (p.eft == allow))

2021-08-18 09:08 UTC, sagilio commented on example/casbinconfig/container_resource_limit.conf
> +m= r.namespace == p.namespace && r.cpu < parseFloat(p.cpu) && r.memory < parseFloat(p.memory)
`m = r.namespace == p.namespace && r.cpu < parseFloat(p.cpu) && r.memory < parseFloat(p.memory)`

2021-08-18 09:23 UTC, sagilio requested changes
I need to prepare the environment for the review of other changes.

2021-08-18 09:23 UTC, sagilio commented on .vscode/settings.json
> +    //"go.testFlags": ["-v"]
`.vscode` should be added in `.gitignore`

2021-08-18 09:23 UTC, sagilio commented on example/casbinconfig/allowed_repo.conf
> +m= r.namespace == p.namespace && r.image == p.image
`m = r.namespace == p.namespace && r.image == p.image `

2021-08-18 09:23 UTC, sagilio commented on example/casbinconfig/container_resource_limit.conf
> +e=some(where (p.eft == allow))
`e = some(where (p.eft == allow))`

2021-08-18 09:23 UTC, sagilio commented on example/casbinconfig/container_resource_limit.conf
> +m= r.namespace == p.namespace && r.cpu < parseFloat(p.cpu) && r.memory < parseFloat(p.memory)
`m = r.namespace == p.namespace && r.cpu < parseFloat(p.cpu) && r.memory < parseFloat(p.memory)`

2021-08-18 09:23 UTC, sagilio commented on example/casbinconfig/container_resource_limit.csv
> +p,default,104857600,104857600,allow
`p, default, 104857600, 104857600, allow`

2021-08-18 09:23 UTC, sagilio commented on example/casbinconfig/permission_model.conf
> +m= r.resourceName == p.resourceName && r.resourceKind == p.resourceKind && r.operation == p.operation
`m = r.resourceName == p.resourceName && r.resourceKind == p.resourceKind && r.operation == p.operation `

2021-08-19 10:00 UTC, sagilio approved these changes

2021-08-19 10:00 UTC, merged